Module1 task2
htmlacademy-yii/375607-task-force-1 pull request #2
Opened 2019-10-14 18:12 UTC by olga028383

2019-10-14 18:33 UTC, caseycs requested changes

2019-10-14 18:33 UTC, caseycs commented on TaskForce.php
> +                //ут не поняла какой статус возвращать
А это потому, что название ACTION_SEND не лучшее. Что означает это действие?

2019-10-14 18:33 UTC, caseycs commented on TaskForce.php
> +        return $status;
Тут тонкий момент - передано неизвестное действие, я в таких случая предпочитаю бросать исключение, из соображений что худшее, что может сделать приложение в нештатной ситуации - сделать вид что все хорошо. Я предпочитаю падать с исключением "на любой чих".

2019-10-14 18:33 UTC, caseycs commented on TaskForce.php
> +            $this->errors[] = 'Задачу в статусе "' . $this->status . '" отменить невозможно';
Лучше бросать исключение

2019-10-14 18:33 UTC, caseycs commented on TaskForce.php
> +                    $actions = array(self::ACTION_CANCEL, self::ACTION_CLOSE);
Т.е. заказчик с новой задачей может сделать два разных действия? А чем они отличаются? Почему те же действия доступны и для уже закрытой задачи?

2019-10-14 18:33 UTC, caseycs commented on TaskForce.php
> +    const STATUS_CLOSED = 'closed';
А что означает closed - успешно выполненная или отмененная?

2019-10-14 18:33 UTC, caseycs commented on TaskForce.php
> +    const ACTION_SEND = 'send';
А что означает send? Отправить кому?

2019-10-14 18:33 UTC, caseycs commented on TaskForce.php
> +    const STATUS_START = 'start';
Тут имеется в виду что задача в состоянии "вот-вот начнется", или в процессе выполнения?

2019-10-14 18:33 UTC, caseycs commented on TaskForce.php
> +    const ACTION_CANCEL = 'cancel';
А в чем отличие между close, fail и cancel?

2019-10-14 18:33 UTC, caseycs commented on TaskForce.php
> +        if ($userRole === self::RIGHTS_CUSTOMER) {
Наверное  ROLE_CUSTOMER?

2019-10-14 18:33 UTC, caseycs commented on TaskForce.php
> +                    $actions = array(self::ACTION_RESPOND, self::ACTION_BEGIN);
По ТЗ исполнителя выбирает заказчик, почему тут begin?

2019-10-14 19:10 UTC, olga028383 commented on TaskForce.php
> +        return $status;
я пробрасываю переменную default и у меня в шторме у переменной $status выводится сообщение Unused local variable 'status'

2019-10-14 19:20 UTC, olga028383 commented on TaskForce.php
> +                    $actions = array(self::ACTION_RESPOND, self::ACTION_BEGIN);
Вот тут я сомневалась, поскольку посчитала, что исполнитель может откликнуться на задачу и начать ее выполнение, а все таки на исполнении ставит статус заказчик

2019-10-16 07:50 UTC, caseycs commented on TaskForce.php
> +    const ACTION_CANCEL = 'cancel';
Сейчас остался один cancel. А как отличить задание, от которого отказался исполнитель от отмененного заказчиком?

2019-10-16 08:20 UTC, caseycs requested changes

2019-10-16 08:20 UTC, caseycs commented on TaskForce.php
> +        if ($this->status !== self::STATUS_EXECUTION || $this->status !== self::STATUS_CLOSED) {
А разве можно отменить закрытую задачу?

2019-10-16 08:20 UTC, caseycs commented on TaskForce.php
> +            self::ACTION_FAIL,
Close, fail и send больше нет

2019-10-16 08:20 UTC, caseycs commented on TaskForce.php
> +            self::STATUS_FAILED
Тут тоже старые константы

2019-10-16 08:20 UTC, caseycs commented on TaskForce.php
> +        return $status;
А как ты понимаешь это сообщение? В каком месте оно показывается?

2019-10-16 08:20 UTC, caseycs commented on TaskForce.php
> +                    $actions = array(self::ACTION_COMPLETE, self::ACTION_CANCEL);
Мне кажется со статусами тут беда. Сверь пожалуйста описания действий с ТЗ, например: https://up.htmlacademy.ru/yii/1/project/task-force#taskforce-4-9

Отмена задания ... Выполняется .... заказчиком ...
Отмена заданий со статусом «На исполнении» невозможна.

2019-10-16 08:22 UTC, caseycs requested changes

2019-10-16 08:22 UTC, caseycs commented on index.php
> +// А как сделать остальные проверки для этого метода? Ведь как только статус изменится эта проверка даст ошибку?
Она выполнится для текущего статуса, потом ты изменишь статус (вызываешь метод действия) - и вызываешь другую проверку.

Также можно сделать несколько объектов с разными статусами.

2019-10-17 07:53 UTC, caseycs commented on TaskForce.php
> +    public function getAvailableActions($userRole)
Есть странности в текущей реализации, но предлагаю на них пока фокусироваться - пункт необязательный, думаю дальше будет яснее.

2019-10-17 07:53 UTC, merged